apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bgdk-replicas
resources:
- ../../base
- bgdk-ns.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
      namespace: bgdk
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
